DROP TABLE IF EXISTS users;

CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL, hash TEXT NOT NULL);


DROP TABLE IF EXISTS expenses;



DROP TABLE IF EXISTS income;