DROP TABLE IF EXISTS users;

CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL, hash TEXT NOT NULL);


DROP TABLE IF EXISTS expenses;
CREATE TABLE expenses (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, category TEXT, description TEXT, purchaseLocation TEXT, quantity INTEGER NOT NULL, price NUMERIC NOT NULL, date TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));


DROP TABLE IF EXISTS income;